# Generated by Django 2.2.5 on 2020-09-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('COFFEE_MACHINE_LARGE', 'coffee_machine_large'), ('COFFEE_MACHINE_SMALL', 'coffee_machine_small'), ('ESPRESSO_MACHINE', 'espresso_machine')], max_length=30)),
                ('water_line_compatible', models.BooleanField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('COFFEE_POD_LARGE', 'coffee_pod_large'), ('COFFEE_POD_SMALL', 'coffee_pod_small'), ('ESPRESSO_POD', 'espresso_pod')], max_length=255)),
                ('coffee_flavor', models.CharField(choices=[('COFFEE_FLAVOR_VANILLA', 'coffee_flavor_vanilla'), ('COFFEE_FLAVOR_CARAMEL', 'coffee_flavor__caramel'), ('COFFEE_FLAVOR_PSL', 'coffee_flavor__psl'), ('COFFEE_FLAVOR_MOCHA', 'coffee_flavor__mocha'), ('COFFEE_FLAVOR_HAZELNUT', 'coffee_flavor__hazelnut')], max_length=255)),
                ('pack_size', models.IntegerField(verbose_name='Size in dozen')),
            ],
        ),
    ]
