# Generated by Django 2.2.5 on 2020-09-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('COFFEE_MACHINE_LARGE', 'COFFEE_MACHINE_LARGE'), ('COFFEE_MACHINE_SMALL', 'COFFEE_MACHINE_SMALL'), ('ESPRESSO_MACHINE', 'ESPRESSO_MACHINE')], default=None, max_length=255)),
                ('water_line_compatible', models.BooleanField(db_index=True, default=None)),
                ('model', models.CharField(choices=[('BASE', 'BASE'), ('PREMIUM', 'PREMIUM'), ('DELUXE', 'DELUXE')], default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('COFFEE_POD_LARGE', 'COFFEE_POD_LARGE'), ('COFFEE_POD_SMALL', 'COFFEE_POD_SMALL'), ('ESPRESSO_POD', 'ESPRESSO_POD')], max_length=255)),
                ('coffee_flavor', models.CharField(choices=[('COFFEE_FLAVOR_VANILLA', 'COFFEE_FLAVOR_VANILLA'), ('COFFEE_FLAVOR_CARAMEL', 'COFFEE_FLAVOR_CARAMEL'), ('COFFEE_FLAVOR_PSL', 'COFFEE_FLAVOR_PSL'), ('COFFEE_FLAVOR_MOCHA', 'COFFEE_FLAVOR_MOCHA'), ('COFFEE_FLAVOR_HAZELNUT', 'COFFEE_FLAVOR_HAZELNUT')], max_length=255)),
                ('pack_size', models.IntegerField(verbose_name='Size in dozen')),
            ],
        ),
    ]
